version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: npm run dev

volumes:
  node_modules:
